name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/ec2.pem
          chmod 600 ~/.ssh/ec2.pem

      - name: SSH into EC2 and deploy
        run: ssh -i ~/.ssh/ec2.pem ubuntu@ec2-34-229-156-26.compute-1.amazonaws.com 'cd /home/ubuntu && ./deploy_script.sh'
