name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main # Changer selon votre branche principale

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.aws.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-west-3 # Changer la région au besoin
        run: aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID && aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY && aws configure set region $AWS_REGION

      - name: Deploy front.py to Elastic Beanstalk
        run: |
          eb deploy --staged --source front.py Riskcredit-env
