name: Deploy front.py to /app on EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Transfer front.py to EC2
        run: scp /app/front.py ec2-user@${{ secrets.EC2_PUBLIC_IP }}:/home/ec2-user
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ec2-user
          key: ${{ secrets.PRODUCTION_MYPROJECT_EC2 }}
          port: 22
          script: |
            cd /app
            # Run any additional commands needed after transferring front.py
