name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run API tests
        run: |
          cd app
          pip3 install -r requirements.txt
          python -m unittest /tests/test_api.py

      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/ec2.pem
          ssh-keyscan ec2-34-229-156-26.compute-1.amazonaws.com >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/ec2.pem

      - name: Transfer code to EC2
        run: |
          scp -i ~/.ssh/ec2.pem -r app ubuntu@ec2-34-229-156-26.compute-1.amazonaws.com:~


      - name: SSH into EC2 and deploy
        run: |
          ssh -i ~/.ssh/ec2.pem -v ubuntu@ec2-34-229-156-26.compute-1.amazonaws.com 'cd ~ && ~/app/deploy_script.sh'
          
