name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install EB CLI
        run: |
          pip install awsebcli --upgrade

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        env:
            VERSION_LABEL: risk-api-${{ github.run_id }}
        with:
            aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            application_name: risk-credit
            environment_name: Risk-credit-env-2
            version_label: ${{ env.VERSION_LABEL }}
            region: us-east-1
            deployment_package: app/front.py