name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install EB CLI
        run: |
          sudo apt-get update
          sudo apt-get install python3-pip
          pip3 install awsebcli --upgrade

      - name: Install dependencies
        run: pip install -r app/requirements.txt

      - name: Create ZIP file
        run: zip -r deployment_package.zip app

      - name: Deploy to EB
        run: |
          eb init -p python-3.11 risk-credit --region us-east-1
          eb deploy --label risk-api-${{ github.run_id }} --staged --timeout 30
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}